### ISSUE TITLE
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Ingress.spec.rules): invalid type for io.k8s.api.extensions.v1beta1.IngressSpec.rules: got "map", expected "array"

### ISSUE THREAD

**Issue by lusson-luo** [liwenhe1993/clickhouse-charts#13]
i open ingress, install failed 
`Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Ingress.spec.rules): invalid type for io.k8s.api.extensions.v1beta1.IngressSpec.rules: got "map", expected "array"`

k8s version: v1.18.20
chart version: 1.0.1

values.yaml
```
  ingress: 
    enabled: true
    host: "clickhouse.domain.com"
    path: "/"
    tls: 
      enabled: false
      hosts: 
      - "clickhouse.domain.com"
      - "clickhouse.domain1.com"
      secretName: "clickhouse-secret"
```

i think error is Ingress template
![image](https://user-images.githubusercontent.com/19859400/191181484-7fcdf7d2-6f90-46c6-b0ad-901b0b1d954c.png)
